# .github/workflows/release.yml
name: Release Build
on:
  push:
    tags:
      - 'v*'  # 当推送 v1.0.0 等标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # 指定 Go 版本

      - name: 多平台编译
        uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux windows darwin  # 目标操作系统
          goarch: amd64 arm64          # 目标架构
          binary_name: yourapp         # 生成文件名前缀
          extra_files: LICENSE README.md  # 附加文件
